name: PHP CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: sqlite3
          coverage: xdebug

      - name: Install dependencies
        run: |
          make install
          npm ci
          npm run build

      - name: Prepare test environment
        run: |
          mkdir -p storage/framework/{cache,sessions,testing,views}
          chmod -R 775 storage bootstrap/cache database
          make setup-test-db

      - name: Run tests
        run: make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
